export const documentComponentComponent: string;
export const code: string;
export const componentType: string;
export const prepend: string;
export const append: string;
export const entered: string;
export const remove: string;
export const exited: string;
export const button: string;
